cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
    path('success/', views.success, name="success"),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.frontpage, name="home"),
    path('contact-us/', views.contactpage, name="contact"),
]

product/urls.py
from . import views
from django.urls import path



app_name = 'product'


urlpatterns = [
    path('search', views.search, name="search"),
    path('<slug:category_slug>/<slug:product_slug>/', views.product, name="product"),
    path('<slug:category_slug>/', views.category, name="category"),
    
]

simple_multivendor_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('vendor/', include('vendor.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from product.models import Product

# Create your views here.

def frontpage(request):
    newest_products = Product.objects.all()[0:8]
    context = {
        'newest_products': newest_products,
    }
    return render(request, 'core/frontpage.html', context)


def contactpage(request):
    return render(request, 'core/contact.html')

templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}Multi Vendor E-Commerce Website{% endblock title %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body>

    <div class="container">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'core:home' %}">
                    <h1 style="font-size: 1rem; text-transform: none; color: white;"><span style="color: crimson;">S</span>iUUU <span style="color: crimson;">S</span>tore</h1>
                </a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                </a>
            </div>



            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                <a class="navbar-item" href="{% url 'core:home' %}">
                    Home
                </a>
                
                {% for category in categories %}
                    <a class="navbar-item" href="{% url 'product:category' category.slug %}">
                        {{category.title}}
                    </a>
                {% endfor %}
                </div>

                <div class="navbar-start">
                    <div class="navbar-item">
                        <form method="get" action="{% url 'product:search' %}">
                            <div class="field has-addons">
                                <div class="control">
                                    <input type="search" name="query" id="" class="input" placeholder="Search...">
                                </div>
                                <div class="control">
                                    <button class="button is-dark is-uppercase">go</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="navbar-end">

                <div class="navbar-item">
                    <a href="{% url 'cart:cart' %}" class="button is-warning">View Cart {% if cart %}({{cart|length}}){% endif %}</a>
                </div>
                
                {% if request.user.is_authenticated %}

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link is-capitalized">
                    {{user.vendor.name}}
                    </a>

                    <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'vendor:vendor-admin' %}">
                        View Profile
                    </a>
                    <a class="navbar-item" href="{% url 'vendor:edit-vendor' %}">
                        Edit Profile
                    </a>
                    <a class="navbar-item" href="{% url 'vendor:add-product' %}">
                        Add Products
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="{% url 'vendor:logout' %}">
                        Signout
                    </a>
                    </div>
                </div>

                {% else %}

                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary" href="{% url 'vendor:become-vendor' %}">
                            <strong>Sign Up</strong>
                        </a>
                        <a class="button is-light" href="{% url 'vendor:login' %}">
                            Log in
                        </a>
                    </div>
                </div>

                {% endif %}


                </div>
            </div>
            </nav>
    </div>


    <div class="backgroundimg">
        <img src="../media/uploads/bg.png">
    </div> 
    
    <section class="section">
        <div class="container">

            {% block content %}{% endblock content %}

        </div>
    </section>


    <footer class="footer">
        <div class="container">
            <h3 class="is-size-4 mb-4">Football Accesories</h3>
            
            {% if request.user.is_authenticated %}
                <a href="{% url 'vendor:vendor-admin' %}">Seller Profile</a>
            {% else %}
                <a href="{% url 'vendor:become-vendor' %}">Start Selling</a>
            {% endif %}

            <br>
            <a href="{% url 'vendor:vendors' %}">List of all Sellers</a>

        </div>
    </footer>
 
    <!-- Footer2 -->
    <section id="footer2" style="background-image: linear-gradient(60deg, #29323c 0%, #485563 100%); align-items: center; min-height: 200px; flex-direction: column; padding-top: 15px; padding-bottom: 10px;">
        <div class="footer container" style="text-align: center; ">
        <div class="brand">
            <h1 style="font-size: 1rem; text-transform: none; color: white; space-between:none;"><span style="color: crimson;">S</span>iUUU <span style="color: crimson;">S</span>tore</h1>
        </div>
        <h2 style="color: white; font-weight: 500; font-size: 15px; letter-spacing: 0.1rem; margin-top: 10px; margin-bottom: 10px;">Follow me</h2>
        <ul class="social-icon" style="justify-content:center; display: flex; flex-direction: row; padding-right: 10px; list-style: none;">
            <li><div class="facebook">
            <a href="https://www.facebook.com/dipson.panta/"><img src="../media/uploads/icon-facebook.png" style ="width: 40px; height: 40px; filter: grayscale(1); transition: 0.3s ease filter; margin: 0 5px;"></a>
            </div></li>
            <li><div class="instagram">
            <a href="https://www.instagram.com/dipson_7/?hl=en"><img src="../media/uploads/icon-instagram.png" style ="width: 40px; height: 40px; filter: grayscale(1); transition: 0.3s ease filter; margin: 0 5px;"></a>
            </div></li>
            <li><div class="youtube">
            <a href="https://www.youtube.com/channel/UCMOw6QgE7tuVieLyrhm4Gbw/featured"><img src="../media/uploads/icon-youtube.png" style ="width: 40px; height: 40px; filter: grayscale(1); transition: 0.3s ease filter; margin: 0 5px;"></a>
            </div></li>
        </ul>
        <p style="color: white; font-size: 12px; align-items: center;">SiUUUStore owned by Dipson. Copyrights @ 2022. All Rights Reserved</p>
        </div>
    </section>

    <script src="{% static 'js/main.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}

</body>
</html>

templates/core/contact.html
{% extends 'core/base.html' %}


{% block title %}Contact Us{% endblock title %}

{% block content %}

    <h1>Contact Us</h1>

    

{% endblock content %}

templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Home Page{% endblock title %}

{% block content %}
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-test-centered mt-6 mb-6">
            <h2 class="is-size-3">Last Added Products</h2>
        </div>

        {% for product in newest_products %}
            {% include 'product/parts/list_item.html' %}
        {% endfor %}
    </div>
{% endblock content %}